using SNM.Twitter.Domain.Enumeration;
using SNM.Twitter.Domain.Twitter;

namespace SNM.Twitter.Application.DTO
{
    public class TwitterChannelPostDto : ModelBaseDto
    {
        public string TwitterPostId { get; set; }
        public DateTime CreatedTime { get; set; }
        public TwitterPostFormatting Formatting { get; set; }
    
        public string Icon { get; set; }
        public string Link { get; set; }
        public string Message { get; set; }
        public string Name { get; set; }
        public string ObjectId { get; set; }
        public string PermalinkUrl { get; set; }
        public string Picture { get; set; } //The picture scraped from any link included with the post.
                                            // public Place Place { get; set; } //Any location information attached to the post.
                                            // public Place Poll { get; set; } //
        public object[] Properties { get; set; } //A list of properties for any attached video, for example, the length of the video.
        public TwitterPostStatusType StatusType { get; set; } //enum {mobile_status_update, created_note, added_photos, added_video, shared_story, created_group, created_event, wall_post, app_created_story, published_story, tagged_in_photo}
        public string Story { get; set; } //Text from stories not intentionally generated by users.
        // public Profile[] To { get; set; } //Text from stories not intentionally generated by users.
        public TwitterPostType Type { get; set; } //Tenum{link, status, photo, video}
        public DateTime UpdatedTime { get; set; } //The time when the post was created, last edited or the time of the last comment that was left on the post.
                                                  // public JSON WithTags { get; set; } //Profiles tagged as being 'with' the publisher of the post.JSON object with a data field that contains a list of Profile objects.
        public Guid TwitterChannelId { get; set; }
        public virtual TwitterChannelDto TwitterChannelDto { get; set; }
        public Guid PostId { get; set; }

        public virtual TwitterTweet TwitterTweet { get; set; }

    }
}
